/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** 
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  myslidebar: [
    {
      type: 'category',
      label: 'Application web',
      items: [
         'Application web/Notre Application',
         'Application web/Premier Pas',
      ],
    },
    {
      type: 'category',
      label: 'FrontEnd',
      items: [
        'FrontEnd/Introduction',
        'FrontEnd/Notre Projet',
       {
        type: 'category',
        label: 'Authentification et Gestion des Comptes',
        items: [
          'FrontEnd/Authentification et Gestion des Comptes/Introduction',
          'FrontEnd/Authentification et Gestion des Comptes/Authentification',
          'FrontEnd/Authentification et Gestion des Comptes/Gestion des Comptes',
          'FrontEnd/Authentification et Gestion des Comptes/Fonctions utilis',
        ],
       },
       {
        type: 'category',
        label: 'Gestion des Fiches Observations',
        items: [
          'FrontEnd/Gestion des Fiches Observations/Introduction',
          'FrontEnd/Gestion des Fiches Observations/Gestion des Fiches',
        ],
       },
       {
        type: 'category',
        label: 'Filtrer par Critère Simple, Site ou Ponctuel',
        items: [
          'FrontEnd/Filtrer par Critère Simple, Site ou Ponctuel/Introduction',
          'FrontEnd/Filtrer par Critère Simple, Site ou Ponctuel/Filtrer',
        ],
       },
      ],
    },
    {
      type: 'category',
      label: 'BackEnd',
      items: [
        'BackEnd/Introduction',
        'BackEnd/Notre Projet',
        'BackEnd/Authentification',
        'BackEnd/Gestion des Comptes',
        
      ],
    },
    
    {
      type: 'category',
      label: 'Migration de base de données',
      items: [
        'Migration de base de données/Introduction',
        {
          type: 'category',
          label: 'Base Access',
          items: [
            'Migration de base de données/Base Access/Base Acces',
            'Migration de base de données/Base Access/Migration Access to MySQL',
          ],
        },
        {
          type: 'category',
          label: 'Base MySQL',
          items: [
            'Migration de base de données/Base MySQL/Doctrine',
            'Migration de base de données/Base MySQL/Nos Entity',
            'Migration de base de données/Base MySQL/Nouvelle LPO',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'GITLAB',
      items: [
        'GITLAB/Générale',
        'GITLAB/Issues',
      ],
    },
    {
      type: 'category',
      label: 'Planning',
      items: [
        'Planning/Sprints',
        'Planning/Suivie des Taches',
      ],
    },
    {
      type: 'category',
      label: 'Guide dutilisation',
      items: [
        'Guide dutilisation/Guide',
      ],
    },

  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'introduction',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
